from enum import StrEnum

class UserRole(StrEnum):
    RENTER = "RENTER"
    ADMIN = "ADMIN"

class SearchStatus(StrEnum):
    DRAFT = "DRAFT"
    ACTIVE = "ACTIVE"
    PAUSED = "PAUSED"
    CLOSED = "CLOSED"

class ListingType(StrEnum):
    ENTIRE_PROPERTY = "ENTIRE_PROPERTY"
    PRIVATE_ROOM = "PRIVATE_ROOM"
    SHARED_ROOM = "SHARED_ROOM"

class ContentType(StrEnum):
    PROPERTY_LISTING = "PROPERTY_LISTING"
    RENTER_REQUIREMENT = "RENTER_REQUIREMENT"
    OTHER = "OTHER"
    UNKNOWN = "UNKNOWN"

class AvailabilityStatus(StrEnum):
    UNKNOWN = "UNKNOWN"
    AVAILABLE = "AVAILABLE"
    UNAVAILABLE = "UNAVAILABLE"
    STALE = "STALE"

class PreferenceImportance(StrEnum):
    REQUIRED = "REQUIRED"
    PREFERRED = "PREFERRED"
    DOES_NOT_MATTER = "DOES_NOT_MATTER"

class MatchStatus(StrEnum):
    REJECTED = "REJECTED"
    POSSIBLE_MATCH = "POSSIBLE_MATCH"
    STRONG_MATCH = "STRONG_MATCH"
    NEEDS_QUALIFICATION = "NEEDS_QUALIFICATION"
    QUALIFIED = "QUALIFIED"
    SKIPPED = "SKIPPED"

class ConversationStatus(StrEnum):
    APPROVED_FOR_CONTACT = "APPROVED_FOR_CONTACT"
    CONTACTED = "CONTACTED"
    AWAITING_REPLY = "AWAITING_REPLY"
    QUALIFYING = "QUALIFYING"
    ESCALATED_TO_RENTER = "ESCALATED_TO_RENTER"
    QUALIFIED = "QUALIFIED"
    READY_FOR_SCHEDULING = "READY_FOR_SCHEDULING"
    NO_RESPONSE = "NO_RESPONSE"
    CLOSED = "CLOSED"

class VisitStatus(StrEnum):
    PROPOSED = "PROPOSED"
    AWAITING_RENTER_CONFIRMATION = "AWAITING_RENTER_CONFIRMATION"
    CONFIRMED = "CONFIRMED"
    CANCELLED = "CANCELLED"
    COMPLETED = "COMPLETED"

class ContactChannelType(StrEnum):
    WHATSAPP = "WHATSAPP"
    EMAIL = "EMAIL"
    PHONE = "PHONE"
    TELEGRAM = "TELEGRAM"

class IngestionStatus(StrEnum):
    COLLECTING_INFO = "COLLECTING_INFO"
    EXTRACTING = "EXTRACTING"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    COLLECTING_MEDIA = "COLLECTING_MEDIA"
    READY_FOR_APPROVAL = "READY_FOR_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
